# Shared Steps for AI and Bulk Actions

Given("the AI will optimize the search query") do
  # Mock OpenAI service to return optimized query
  allow_any_instance_of(OpenaiService).to receive(:generate_search_query).and_return("optimized query")

  # Stub the search for the optimized query
  # We stub both show and episode search structures to cover both cases
  stub_request(:any, /search/)
    .to_return(status: 200, body: {
      shows: {
        items: [
          { id: "opt_show_1", name: "Optimized Result", publisher: "Pub", images: [], external_urls: { spotify: "url" }, total_episodes: 10 }
        ],
        total: 1
      },
      episodes: {
        items: [
          { id: "opt_ep_1", name: "Optimized Result", show: { name: "Show" }, images: [], external_urls: { spotify: "url" }, duration_ms: 60000, release_date: "2023-01-01" }
        ],
        total: 1
      }
    }.to_json)
end

Then("the search query should be optimized by AI") do
  # Verification is done by the fact that the search succeeded with the optimized query stub
end

Then("I should see search results for the optimized query") do
  expect(page).to have_content("Optimized Result")
end

Then("I should see bulk recommendations generated by AI") do
  expect(page).to have_content("Bulk Rec 1")
end

Given("Spotify API returns success for bulk show save") do
  stub_request(:put, /https:\/\/api\.spotify\.com\/v1\/me\/shows/)
    .to_return(status: 200)
end

Given("Spotify API raises an error {string} during bulk show save") do |error_message|
  stub_request(:put, /https:\/\/api\.spotify\.com\/v1\/me\/shows/)
    .to_return(status: 500, body: { error: { message: error_message } }.to_json)
end

# Click-only steps for error scenarios (Shared)

When("I click {string} for the first result without stubbing") do |button_text|
  first(:button, title: button_text).click
end

When("I click {string} for the first show without stubbing") do |button_text|
  first(:button, title: button_text).click
end

When("I click the recommendation button {string} for the first show without stubbing") do |button_text|
  # Find by text content since title might be different
  click_button button_text
end

When("I click the recommendation button {string} for the first show") do |button_text|
  # Stub get_show for the show ID (which is "1" from "I have saved shows")
  stub_request(:get, "https://api.spotify.com/v1/shows/1")
    .to_return(status: 200, body: { id: "1", name: "Saved Show", publisher: "Pub" }.to_json)

  if button_text == "Why?"
    allow_any_instance_of(OpenaiService).to receive(:generate_recommendation).and_return("Because you like it.")
  elsif button_text == "Similar"
    allow_any_instance_of(OpenaiService).to receive(:suggest_similar_shows).and_return([ "Similar Show 1" ])
    stub_request(:get, /https:\/\/api\.spotify\.com\/v1\/search/)
      .to_return(status: 200, body: { shows: { items: [ { id: "sim_1", name: "Similar Show 1", publisher: "Pub", images: [], external_urls: { spotify: "url" }, total_episodes: 10 } ], total: 1 } }.to_json)
  end

  click_button button_text
end

When("I search for {string} without stubbing") do |query|
  fill_in "query", with: query
  click_button "Search"
end
