Feature: Saved Episodes
  As a user
  I want to manage my saved episodes
  So that I can keep track of specific podcast episodes I like

  Background:
    Given I am logged in to Spotify

  Scenario: View saved episodes successfully
    Given I have saved episodes
    When I visit the saved episodes page
    Then I should see a list of my saved episodes
    And I should see pagination controls

  Scenario: View saved episodes with API error
    Given Spotify API raises an error "Service Unavailable" for episodes
    When I visit the saved episodes page
    Then I should see "Could not load saved episodes"

  Scenario: View saved episodes when session expired
    Given Spotify API raises an unauthorized error for episodes
    When I visit the saved episodes page
    Then I should be redirected to the home page
    And I should see "Session expired. Please sign in again."

  Scenario: Search and save an episode successfully
    When I visit the saved episodes page
    And I click "Find New Episodes"
    And I search for "Tech"
    Then I should see search results for "Tech"
    When I click "Save to Library" for the first result
    Then I should see "Episode saved to your library"

  Scenario: Search for episodes with API error
    When I visit the saved episodes page
    And I click "Find New Episodes"
    Given Spotify API raises an error "Search Failed" during search
    And I search for "Tech" without stubbing
    Then I should see "Could not search for episodes"

  Scenario: Save an episode with API error
    When I visit the saved episodes page
    And I click "Find New Episodes"
    And I search for "Tech"
    Given Spotify API raises an error "Save Failed" during episode save
    When I click "Save to Library" for the first result without stubbing
    Then I should see "Could not save episode"

  Scenario: Remove a saved episode successfully
    Given I have saved episodes
    When I visit the saved episodes page
    And I click "Remove from Library" for the first episode
    Then I should see "Episode removed from your library"

  Scenario: Remove a saved episode with API error
    Given I have saved episodes
    When I visit the saved episodes page
    Given Spotify API raises an error "Remove Failed" during episode remove
    And I click "Remove from Library" for the first episode without stubbing
    Then I should see "Could not remove episode"

  Scenario: Empty state
    Given I have no saved episodes
    When I visit the saved episodes page
    Then I should see "You haven't saved any episodes yet"

  Scenario: AI Smart Search
    When I visit the saved episodes search page
    And I check "AI Search"
    Given the AI will optimize the search query
    And I search for "tech news"
    Then the search query should be optimized by AI
    And I should see search results for the optimized query

  Scenario: Episode Summary
    Given I have saved episodes
    When I visit the saved episodes page
    And I click the button "Summarize Episode (AI)" for the first episode
    Then I should see "Summary generated."

  Scenario: Episode Summary Error
    Given I have saved episodes
    When I visit the saved episodes page
    Given Spotify API raises an error "Summary Failed" during summary
    And I click the button "Summarize Episode (AI)" for the first episode without stubbing
    Then I should see "Could not summarize episode."

  Scenario: Bulk Recommendations
    Given I have saved episodes
    When I visit the saved episodes page
    And I click the episode bulk recommendations link
    Then I should see bulk recommendations generated by AI

  Scenario: Bulk Recommendations Error
    Given I have saved episodes
    When I visit the saved episodes page
    Given Spotify API raises an error "Bulk Failed" during episode bulk recommendations
    And I click the episode bulk recommendations link
    Then I should see "Could not generate recommendations"

  Scenario: Bulk Recommendations Empty
    Given I have no saved episodes
    When I visit the saved episodes page
    And I click the episode bulk recommendations link
    Then I should see "You need to save some episodes first!"

  Scenario: Bulk Save
    Given I have saved episodes
    When I visit the saved episodes page
    And I click the episode bulk recommendations link
    Given Spotify API returns success for bulk episode save
    And I click the button "Save All"
    Then I should see "Saved 1 episodes to your library"

  Scenario: Bulk Save Error
    Given I have saved episodes
    When I visit the saved episodes page
    And I click the episode bulk recommendations link
    Given Spotify API raises an error "Bulk Save Failed" during bulk episode save
    And I click the button "Save All"
    Then I should see "Could not save episodes"

  Scenario: Group by Show
    Given I have saved episodes
    When I visit the saved episodes page
    And I click "Group by Show"
    Then I should see episodes grouped by show
