Feature: Saved Shows
  As a user
  I want to manage my saved shows
  So that I can keep track of podcasts I like

  Background:
    Given I am logged in to Spotify

  Scenario: View saved shows successfully
    Given I have saved shows
    When I visit the saved shows page
    Then I should see a list of my saved shows
    And I should see pagination controls

  Scenario: View saved shows with API error
    Given Spotify API raises an error "Service Unavailable"
    When I visit the saved shows page
    Then I should see "Could not load saved shows"

  Scenario: View saved shows when session expired
    Given Spotify API raises an unauthorized error
    When I visit the saved shows page
    Then I should be redirected to the home page
    And I should see "Session expired. Please sign in again."

  Scenario: Search and save a show successfully
    When I visit the saved shows page
    And I click "Find New Shows"
    And I search for "News"
    Then I should see search results for "News"
    When I click "Save to Library" for the first result
    Then I should see "Show saved to your library"

  Scenario: Search for shows with API error
    When I visit the saved shows page
    And I click "Find New Shows"
    Given Spotify API raises an error "Search Failed" during search
    And I search for "News" without stubbing
    Then I should see "Could not search for shows"

  Scenario: Save a show with API error
    When I visit the saved shows page
    And I click "Find New Shows"
    And I search for "News"
    Given Spotify API raises an error "Save Failed" during show save
    When I click "Save to Library" for the first result without stubbing
    Then I should see "Could not save show"

  Scenario: Remove a saved show successfully
    Given I have saved shows
    When I visit the saved shows page
    And I click "Remove from Library" for the first show
    Then I should see "Show removed from your library"

  Scenario: Remove a saved show with API error
    Given I have saved shows
    When I visit the saved shows page
    Given Spotify API raises an error "Remove Failed" during show remove
    And I click "Remove from Library" for the first show without stubbing
    Then I should see "Could not remove show"

  Scenario: Empty state
    Given I have no saved shows
    When I visit the saved shows page
    Then I should see "You haven't saved any shows yet"

  Scenario: AI Smart Search
    When I visit the saved shows search page
    And I check "AI Search"
    Given the AI will optimize the search query
    And I search for "tech news"
    Then the search query should be optimized by AI
    And I should see search results for the optimized query

  Scenario: Show Recommendations
    Given I have saved shows
    When I visit the saved shows page
    And I click the recommendation button "Why?" for the first show
    Then I should see "Recommendation generated."

  Scenario: Show Recommendations Error
    Given I have saved shows
    When I visit the saved shows page
    Given Spotify API raises an error "Recommendation Failed" during recommendation
    And I click the recommendation button "Why?" for the first show without stubbing
    Then I should see "Could not generate recommendation"

  Scenario: Similar Shows
    Given I have saved shows
    When I visit the saved shows page
    And I click the recommendation button "Similar" for the first show
    Then I should see "Found 1 similar shows."

  Scenario: Similar Shows Error
    Given I have saved shows
    When I visit the saved shows page
    Given Spotify API raises an error "Similar Failed" during similar
    And I click the recommendation button "Similar" for the first show
    Then I should see "Could not find similar shows"

  Scenario: Bulk Recommendations
    Given I have saved shows
    When I visit the saved shows page
    And I click the bulk recommendations link
    Then I should see bulk recommendations generated by AI

  Scenario: Bulk Recommendations Error
    Given I have saved shows
    When I visit the saved shows page
    Given Spotify API raises an error "Bulk Failed" during bulk recommendations
    And I click the bulk recommendations link
    Then I should see "Could not generate recommendations"

  Scenario: Bulk Recommendations Empty
    Given I have no saved shows
    When I visit the saved shows page
    And I click the bulk recommendations link
    Then I should see "You need to save some shows first!"

  Scenario: Bulk Save
    Given I have saved shows
    When I visit the saved shows page
    And I click the bulk recommendations link
    Given Spotify API returns success for bulk show save
    And I click the button "Save All"
    Then I should see "Saved 1 shows to your library"

  Scenario: Bulk Save Error
    Given I have saved shows
    When I visit the saved shows page
    And I click the bulk recommendations link
    Given Spotify API raises an error "Bulk Save Failed" during bulk show save
    And I click the button "Save All"
    Then I should see "Could not save shows"
